//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class safaricom_regions
    {
        public string Region { get; set; }
        public string Sales_Area { get; set; }
        public string Cluster { get; set; }
        public int Id { get; set; }
    }
}
